### PR TITLE
Use gc instead of !gccgo build tags

### PR DESCRIPTION
**Pull request by tamird**
This is more correct since this assembly syntax is specific to gc.

### CODE REVIEW

**Comment by dgryski** [comment]
Looking at the standard library, it seems `!gccgo` is *way* more frequent that `gc`.

**Comment by tamird** [comment]
Yeah, I plan to make this change there, too. Since `llvmgo` is now an
official-ish project, I imagine this will start to matter.

**Comment by tamird** [comment]
Upstream is accepting this sort of change.

https://go-review.googlesource.com/c/sys/+/269717

**Comment by tamird** [comment]
@dgryski ping.

**Comment by dgryski** [comment]
Sure.  Thanks!

**Pull request merged**
